#!/usr/bin/env python3
"""Setup script for Cloude Code authentication.

Generates TOTP secret and JWT secret, creates config file.
"""
import json
import secrets
import subprocess
import sys
from pathlib import Path


def check_and_setup_venv():
    """Ensure venv exists and has required packages."""
    # Get venv path
    project_root = Path(__file__).parent
    venv_path = project_root / "venv"
    venv_python = venv_path / "bin" / "python3"

    # Check if venv exists
    if not venv_python.exists():
        print("❌ venv not found at: venv/")
        print("Please create it first:")
        print("  python3 -m venv venv")
        sys.exit(1)

    # Check if dependencies are installed
    try:
        import pyotp
        import qrcode
        import jwt
        print("✅ All dependencies available\n")
        return
    except ImportError as e:
        missing_module = str(e).split("'")[1] if "'" in str(e) else "unknown"
        print(f"📦 Missing dependency: {missing_module}")
        print("Installing auth dependencies in venv...\n")

    # Install dependencies
    try:
        result = subprocess.run([
            str(venv_python), "-m", "pip", "install", "-q",
            "pyotp", "qrcode", "pillow", "pyjwt"
        ], check=True, capture_output=True, text=True)

        print("✅ Dependencies installed successfully\n")

        # Re-exec with venv python
        print("🔄 Re-running with venv python...\n")
        subprocess.run([str(venv_python), __file__] + sys.argv[1:])
        sys.exit(0)

    except subprocess.CalledProcessError as e:
        print(f"❌ Failed to install dependencies: {e}")
        print(f"Error output: {e.stderr}")
        sys.exit(1)


def generate_totp_secret():
    """Generate a random TOTP secret."""
    import pyotp
    return pyotp.random_base32()


def generate_jwt_secret():
    """Generate a random JWT secret."""
    return secrets.token_urlsafe(32)


def update_env_file(env_path: Path, totp_secret: str, jwt_secret: str):
    """Update .env file with generated secrets."""
    # Read existing .env or create from .env.example
    if env_path.exists():
        with open(env_path) as f:
            lines = f.readlines()
    else:
        # Start from .env.example
        example_path = env_path.parent / ".env.example"
        if example_path.exists():
            with open(example_path) as f:
                lines = f.readlines()
        else:
            lines = []

    # Update or add TOTP_SECRET and JWT_SECRET
    totp_found = False
    jwt_found = False

    for i, line in enumerate(lines):
        if line.startswith("TOTP_SECRET="):
            lines[i] = f"TOTP_SECRET={totp_secret}\n"
            totp_found = True
        elif line.startswith("JWT_SECRET="):
            lines[i] = f"JWT_SECRET={jwt_secret}\n"
            jwt_found = True

    # Add if not found
    if not totp_found:
        # Find a good place to insert (after # Authentication Secrets comment if it exists)
        insert_index = len(lines)
        for i, line in enumerate(lines):
            if "# Authentication Secrets" in line:
                insert_index = i + 2  # After comment and blank TOTP_SECRET=
                break

        if insert_index >= len(lines):
            lines.append(f"\n# Authentication Secrets (generated by setup_auth.py)\n")
            lines.append(f"TOTP_SECRET={totp_secret}\n")
        else:
            lines.insert(insert_index, f"TOTP_SECRET={totp_secret}\n")

    if not jwt_found:
        # Add right after TOTP_SECRET
        for i, line in enumerate(lines):
            if line.startswith("TOTP_SECRET="):
                lines.insert(i + 1, f"JWT_SECRET={jwt_secret}\n")
                break
        else:
            lines.append(f"JWT_SECRET={jwt_secret}\n")

    # Write back
    with open(env_path, 'w') as f:
        f.writelines(lines)


def generate_qr_code(secret: str, account_name: str = "Cloude Code"):
    """Generate QR code for TOTP secret."""
    import pyotp
    import qrcode

    totp = pyotp.TOTP(secret)
    uri = totp.provisioning_uri(
        name=account_name,
        issuer_name="Cloude Code"
    )

    # Generate QR code
    qr = qrcode.QRCode(version=1, box_size=10, border=5)
    qr.add_data(uri)
    qr.make(fit=True)

    # Print ASCII QR code to terminal
    qr.print_ascii()

    # Also save as image to project directory
    img = qr.make_image(fill_color="black", back_color="white")
    qr_path = Path(__file__).parent / "totp-qr.png"
    img.save(str(qr_path))

    return uri, qr_path

def prompt_with_default(prompt_text, default_value=""):
    """Prompt user for input with optional default value."""
    if default_value:
        user_input = input(f"{prompt_text} [{default_value}]: ").strip()
        return user_input if user_input else default_value
    else:
        return input(f"{prompt_text}: ").strip()


def setup_env_file(env_path):
    """Interactive setup for .env file configuration."""
    print("=" * 70)
    print("Cloudflare Configuration")
    print("=" * 70)
    print()
    print("You'll need:")
    print("  1. A Cloudflare account and domain")
    print("  2. API token (with Zone.DNS and Tunnel permissions)")
    print("  3. Your Cloudflare Zone ID")
    print()

    # Get current values if .env exists
    current_values = {}
    if env_path.exists():
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    current_values[key] = value

    # Prompt for values
    cf_domain = prompt_with_default(
        "Cloudflare domain (e.g., claude.yourdomain.com)",
        current_values.get('CLOUDFLARE_DOMAIN', 'cloude.example.com')
    )

    print()
    print("To get your Cloudflare credentials:")
    print("  API Token: https://dash.cloudflare.com/profile/api-tokens")
    print("  Zone ID: Found on your domain's overview page")
    print()

    cf_token = prompt_with_default(
        "Cloudflare API token",
        current_values.get('CLOUDFLARE_API_TOKEN', '')
    )

    cf_zone = prompt_with_default(
        "Cloudflare Zone ID",
        current_values.get('CLOUDFLARE_ZONE_ID', '')
    )

    cf_tunnel_name = prompt_with_default(
        "Tunnel name",
        current_values.get('CLOUDFLARE_TUNNEL_NAME', 'cloude-controller')
    )

    # Update .env file with all values
    env_template_path = env_path.parent / ".env.example"
    if env_template_path.exists():
        with open(env_template_path) as f:
            content = f.read()
    else:
        # Minimal template if .env.example doesn't exist
        content = (
            "CLOUDFLARE_API_TOKEN=\n"
            "CLOUDFLARE_ZONE_ID=\n"
            "CLOUDFLARE_DOMAIN=\n"
            "CLOUDFLARE_TUNNEL_NAME=\n"
            "TOTP_SECRET=\n"
            "JWT_SECRET=\n"
        )

    # Replace placeholders
    content = content.replace(f"CLOUDFLARE_DOMAIN={current_values.get('CLOUDFLARE_DOMAIN', 'cloude.mydomain.nyc')}",
                             f"CLOUDFLARE_DOMAIN={cf_domain}")
    content = content.replace("CLOUDFLARE_API_TOKEN=", f"CLOUDFLARE_API_TOKEN={cf_token}")
    content = content.replace("CLOUDFLARE_ZONE_ID=", f"CLOUDFLARE_ZONE_ID={cf_zone}")
    content = content.replace(f"CLOUDFLARE_TUNNEL_NAME={current_values.get('CLOUDFLARE_TUNNEL_NAME', 'cloude-controller')}",
                             f"CLOUDFLARE_TUNNEL_NAME={cf_tunnel_name}")

    # Write .env
    with open(env_path, 'w') as f:
        f.write(content)

    print()
    print(f"✅ Configuration written to {env_path}")
    print()

    return cf_domain, cf_token, cf_zone, cf_tunnel_name


def main():
    """Main setup function."""
    # Ensure venv has required dependencies
    check_and_setup_venv()

    print("=" * 70)
    print("Cloude Code Authentication Setup")
    print("=" * 70)
    print()

    # Project root
    project_root = Path(__file__).parent
    env_path = project_root / ".env"

    # Interactive .env setup
    cf_domain, cf_token, cf_zone, cf_tunnel_name = setup_env_file(env_path)

    # Generate new secrets
    totp_secret = generate_totp_secret()
    jwt_secret = generate_jwt_secret()
    print("🔑 Generated new authentication secrets\n")

    # Update .env file with secrets
    print(f"Adding authentication secrets to .env...")
    update_env_file(env_path, totp_secret, jwt_secret)
    print(f"✅ Secrets added to .env\n")

    # Config file in project directory
    config_path = project_root / "config.json"

    # Check if config already exists
    if config_path.exists():
        print(f"📄 Config file exists at: {config_path}")

        # Remove secrets from existing config if they're there
        try:
            with open(config_path) as f:
                data = json.load(f)

            if "totp_secret" in data or "jwt_secret" in data:
                data.pop("totp_secret", None)
                data.pop("jwt_secret", None)

                with open(config_path, 'w') as f:
                    json.dump(data, f, indent=2)

                print("✅ Removed secrets from config.json (now in .env)\n")
            else:
                print("✅ Config file already clean (no secrets)\n")

        except Exception as e:
            print(f"⚠️  Error cleaning config: {e}\n")

    else:
        # Create new config from example
        example_path = project_root / "config.example.json"
        with open(example_path) as f:
            config = json.load(f)

        # Remove secrets from config (they're in .env now)
        config.pop("totp_secret", None)
        config.pop("jwt_secret", None)

        # Write config WITHOUT secrets
        with open(config_path, "w") as f:
            json.dump(config, f, indent=2)

        print(f"✅ Configuration file created at: {config_path}\n")

    print("=" * 70)
    print("TOTP Setup")
    print("=" * 70)
    print()

    # Generate and display QR code
    uri, qr_path = generate_qr_code(totp_secret)

    # Open QR code with Preview
    print()
    print(f"📱 Opening QR code...")
    try:
        subprocess.run(['open', str(qr_path)], check=False)
        print(f"✅ QR code opened in Preview: {qr_path}")
    except Exception as e:
        print(f"⚠️  Could not open QR code automatically: {e}")
        print(f"   Please open manually: {qr_path}")

    print()
    print("=" * 70)
    print(f"📱 SCAN THE QR CODE that just opened in Preview!")
    print("=" * 70)
    print()
    print("Use Google Authenticator, Authy, or any TOTP app")
    print()
    print(f"Or manually enter this secret: {totp_secret}")
    print()

    input("Press Enter after scanning the QR code...")

    print()
    print("=" * 70)
    print("Setup Complete!")
    print("=" * 70)
    print()
    print(f"✅ Configuration: {env_path}")
    print(f"✅ App config: {config_path}")
    print()
    print("You can find and modify the app config here:")
    print(f"   {config_path}")
    print()
    print("Starting Cloude Code server...")
    print()

    # Start the server
    try:
        venv_python = project_root / "venv" / "bin" / "python3"
        if venv_python.exists():
            subprocess.Popen([str(venv_python), '-m', 'src.main'],
                           cwd=str(project_root),
                           stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL)
            print("✅ Server started in background")
        else:
            print("⚠️  Could not find venv, please start server manually with: ./start.sh")
    except Exception as e:
        print(f"⚠️  Could not start server: {e}")
        print("   Start manually with: ./start.sh")

    print()
    print("This window will close in 3 seconds...")
    import time
    time.sleep(3)

    # Close terminal window
    subprocess.run(['osascript', '-e', 'tell application "Terminal" to close first window'],
                  check=False)

if __name__ == "__main__":
    main()
