"""Portable shape coverage: reassembly rebuilds hand-authored lines exactly.

RUNS EVERYWHERE, INCLUDING CI. The corpus fidelity suite is the stronger
proof but needs a 15 GB database that exists on one machine. This module
needs nothing but the repo, so the reassembly guarantee has a defence in
every environment.

HOW CIRCULARITY WAS AVOIDED. Stated in full in
``tests/jsonl_shape_fixture_data``, and worth repeating because it is the
one property that makes this file worth anything: every expected line is
a HAND-AUTHORED literal, never program output. The inputs handed to the
code under test are derived from that literal by a dependency-free
splitter in the fixture module, and each fixture's ``key_order`` is
hand-declared rather than derived at all. So neither side of any
assertion below is produced by ``reassemble`` or ``render_with_style``,
which are the functions being tested. Had the fixtures been generated by
running the exporter, this suite would pass unchanged while reassembly
rotted.

WHY 30 FIXTURES AND NOT 1,347. Reassembly walks a key order and serializes
the result; it cannot branch on ``model``, ``record_type``, ``role`` or the
other body VALUES the census counts, because those ride inside the body
opaquely. :func:`test_the_six_reassembly_classes_cover_every_signature`
proves that claim against the manifest rather than asserting it in prose:
it projects all 1,347 signatures onto the dimensions reassembly can branch
on and requires the result to be exactly the classes covered here.
"""

from __future__ import annotations

import json
from typing import Dict, Tuple

import pytest

from src.core.message_model_serialize import (
    APPEARANCE_KEYS,
    KEY_ORDER_NOT_AN_OBJECT,
    STYLE_NAMES,
    reassemble,
    render_line,
)
from tests.jsonl_shape_fixture_data import (
    ENVELOPE_KEYS,
    FIXTURES,
    NOT_AN_OBJECT,
    ShapeFixture,
    split_line,
)
from tests.jsonl_shape_support import load_manifest

#: The dimensions reassembly can actually branch on. Everything else the
#: census tracks is a value carried inside the body and cannot change how
#: a line is rebuilt. ``key_order_len`` is excluded deliberately: walking
#: a list of 15 keys and a list of 3 is the same code path, and including
#: it would inflate 6 honest classes into 44 restatements of one.
REASSEMBLY_DIMENSIONS: Tuple[str, ...] = (
    "line_status", "serializer_style", "render_source", "body_row",
    "envelope_keys", "line_ending", "has_trailing_newline",
    "body_toplevel_type",
)

#: The number of distinct reassembly classes the corpus actually contains,
#: measured by projecting all 1,347 signatures onto
#: REASSEMBLY_DIMENSIONS. Pinned so that a corpus growing a seventh class
#: fails here and forces a fixture rather than passing unnoticed.
EXPECTED_REASSEMBLY_CLASSES: int = 6


@pytest.mark.parametrize("fixture", FIXTURES, ids=lambda f: f.name)
def test_reassembly_reproduces_the_hand_authored_line(fixture: ShapeFixture):
    """Production reassembly rebuilds each hand-authored line byte-exact."""
    body, envelope = split_line(fixture.line, fixture.key_order)
    key_order = (
        KEY_ORDER_NOT_AN_OBJECT if fixture.key_order == NOT_AN_OBJECT
        else fixture.key_order
    )
    produced = render_line(body, envelope, key_order, fixture.style)
    assert produced == fixture.line, (
        f"reassembly no longer reproduces {fixture.name}\n"
        f"  covers:   {fixture.covers}\n"
        f"  expected: {fixture.line!r}\n"
        f"  produced: {produced!r}"
    )


@pytest.mark.parametrize("fixture", FIXTURES, ids=lambda f: f.name)
def test_envelope_split_matches_what_the_fixture_declares(
    fixture: ShapeFixture,
):
    """Each fixture's envelope is the key set it says it is.

    Description: guards the fixtures themselves. A fixture that claims to
      cover the agentId-without-isSidechain state while actually carrying
      neither key would pass the reassembly test above and cover nothing.
    """
    _, envelope = split_line(fixture.line, fixture.key_order)
    assert sorted(envelope) == sorted(fixture.envelope_keys_expected), (
        f"{fixture.name} declares envelope keys "
        f"{sorted(fixture.envelope_keys_expected)} but carries "
        f"{sorted(envelope)}"
    )


@pytest.mark.parametrize("fixture", FIXTURES, ids=lambda f: f.name)
def test_reassemble_restores_key_order_position_for_position(
    fixture: ShapeFixture,
):
    """Reassembly puts every key back at its declared index.

    Description: the byte comparison above would also catch this, but it
      reports "these two strings differ" for every cause. This one names
      the ordering directly, so a reordering bug is legible as one.
    """
    if fixture.key_order == NOT_AN_OBJECT:
        pytest.skip("a non-object line has no key order to restore")
    body, envelope = split_line(fixture.line, fixture.key_order)
    rebuilt = reassemble(body, envelope, fixture.key_order)
    assert list(rebuilt.keys()) == list(fixture.key_order)


def test_appearance_key_set_has_not_changed():
    """The fixtures' hand-declared envelope key set matches production.

    Description: the fixture module declares ENVELOPE_KEYS by hand rather
      than importing it, so that adding a third appearance key shows up
      here as one failing assertion instead of silently changing what
      every fixture covers.
    """
    assert tuple(ENVELOPE_KEYS) == tuple(APPEARANCE_KEYS), (
        "APPEARANCE_KEYS changed. Every fixture's envelope split is now "
        "describing a different partition; review them, then update "
        "ENVELOPE_KEYS in tests/jsonl_shape_fixture_data.py"
    )
    assert NOT_AN_OBJECT == KEY_ORDER_NOT_AN_OBJECT


def test_every_registered_serializer_style_has_a_fixture():
    """All four registered styles are exercised, not only the two live ones.

    Description: two of the four styles have zero corpus rows, so without
      this the style table's other half would be untested everywhere.
    """
    covered = {fixture.style for fixture in FIXTURES}
    missing = sorted(set(STYLE_NAMES) - covered)
    assert not missing, f"no fixture exercises these styles: {missing}"


def _reassembly_class(dimensions: Dict[str, object]) -> str:
    """Project one signature's dimensions onto the reassembly axes.

    Inputs: dimensions (dict - a manifest signature's dimensions).
    Output: str - a canonical, comparable class key.
    Example: _reassembly_class({...})[:11] -> '{"body_row"'
    """
    return json.dumps(
        {name: dimensions[name] for name in REASSEMBLY_DIMENSIONS},
        sort_keys=True, separators=(",", ":"),
    )


def test_the_six_reassembly_classes_cover_every_signature():
    """All 1,347 manifest signatures collapse to the classes covered here.

    Description: the justification for not writing 1,347 fixtures, proven
      rather than asserted. If a future census finds a seventh class, this
      fails and names it, which is the intended outcome - a new reassembly
      path needs a fixture, not a bigger number here.
    """
    manifest = load_manifest()
    classes: Dict[str, int] = {}
    for entry in manifest["signatures"]:
        key = _reassembly_class(entry["dimensions"])
        classes[key] = classes.get(key, 0) + 1
    assert len(classes) == EXPECTED_REASSEMBLY_CLASSES, (
        f"the corpus now holds {len(classes)} distinct reassembly classes, "
        f"not {EXPECTED_REASSEMBLY_CLASSES}. Every class needs a hand-"
        "authored fixture before this number is raised:\n"
        + "\n".join(f"  {count:5d} signatures  {key}"
                    for key, count in sorted(classes.items(),
                                             key=lambda kv: -kv[1]))
    )
    assert sum(classes.values()) == len(manifest["signatures"])


def test_fixture_names_and_lines_are_unique():
    """No two fixtures share a name or silently duplicate a line.

    Description: a duplicated line is coverage that looks like two paths
      and is one, which is how a coverage count overstates itself.
    """
    names = [fixture.name for fixture in FIXTURES]
    assert len(set(names)) == len(names), "duplicate fixture name"
    lines = [fixture.line for fixture in FIXTURES]
    assert len(set(lines)) == len(lines), "two fixtures carry the same line"


def test_fixture_lines_are_single_lines():
    """No fixture literal contains a raw newline.

    Description: a JSONL line is one line by definition. A raw newline in
      a literal would make the fixture describe something the format
      cannot hold, and the failure would surface far from here.
    """
    for fixture in FIXTURES:
        assert "\n" not in fixture.line, (
            f"{fixture.name} contains a raw newline; escape it as \\n "
            "inside the JSON string instead"
        )
