"""The message gate contract: registry totality, fidelity's three
outcomes, decision application, and the reaper interlock.

The properties pinned here are the ones that make the contract worth
having, same rationale as test_hook_contract.py: a condition that can be
added to the vocabulary without a recorded severity/description, or a
reaper that can be fooled into eligibility by a gated item, would look
exactly like a working gate right up until it was not.
"""

import pytest

from src.core.message_gate_contract import (
    ADVISORY_CODES,
    ALL_DISPOSABILITY_SIGNAL_KINDS,
    ALL_FIDELITY_OUTCOMES,
    ALL_ITEM_STATUSES,
    ALL_REAP_VERDICTS,
    ALL_SEVERITIES,
    AUTO_RESOLVABLE_CODES,
    BY_CODE,
    Candidate,
    DISPOSABILITY_HUMAN_DECISION,
    DisposabilitySignal,
    FIDELITY_FAILED,
    FIDELITY_UNVERIFIABLE,
    FIDELITY_VERIFIED,
    GATE_CONDITIONS,
    GATE_DANGLING_PARENT,
    GATE_TOOL_CALL_WITHOUT_RESULT,
    GateCondition,
    GateDecision,
    GatedItem,
    KNOWN_RECORD_TYPES,
    RECORD_TYPES_WITHOUT_TIMESTAMPS,
    REAP_BLOCKED_GATED,
    REAP_BLOCKED_NO_SIGNAL,
    REAP_ELIGIBLE,
    SEVERITY_ADVISORY,
    SEVERITY_STOP,
    STATUS_AUTO_RESOLVED,
    STATUS_GATED,
    STATUS_RESOLVED,
    STOP_CODES,
    apply_decision,
    auto_resolve,
    classify_fidelity,
    reap_eligibility,
)


# ---- registry totality -------------------------------------------------

def test_every_condition_has_exactly_one_registry_row():
    codes = [c.code for c in GATE_CONDITIONS]
    assert len(codes) == len(set(codes)), "a gate condition is registered twice"
    assert set(codes) == set(BY_CODE)


def test_every_condition_has_a_valid_severity_and_nonblank_description():
    for c in GATE_CONDITIONS:
        assert c.severity in ALL_SEVERITIES
        assert c.description, f"{c.code} has a blank description"


def test_severity_partition_is_total_and_disjoint():
    """Every condition is in exactly one of STOP or ADVISORY."""
    all_codes = {c.code for c in GATE_CONDITIONS}
    assert STOP_CODES | ADVISORY_CODES == all_codes
    assert STOP_CODES & ADVISORY_CODES == set()


def test_auto_resolvable_codes_are_a_subset_of_registered_codes():
    assert AUTO_RESOLVABLE_CODES <= {c.code for c in GATE_CONDITIONS}


def test_gate_condition_rejects_unknown_severity():
    with pytest.raises(ValueError):
        GateCondition("x", "not_a_severity", False, "desc")


def test_gate_condition_rejects_blank_description():
    with pytest.raises(ValueError):
        GateCondition("x", SEVERITY_STOP, False, "")


def test_known_record_types_and_timestamp_exempt_set_agree():
    """Every record_type allowed to have a NULL timestamp must itself be
    a known record_type - the exemption cannot name something outside
    the measured vocabulary."""
    assert RECORD_TYPES_WITHOUT_TIMESTAMPS <= KNOWN_RECORD_TYPES


# ---- fidelity: three outcomes, never collapsed -------------------------

def test_fidelity_verified_when_bytes_match():
    result = classify_fidelity(
        bytes_match=True, source_available=True, has_stored_hash=False,
        detail="regenerated from parsed fields, matched source line",
    )
    assert result.outcome == FIDELITY_VERIFIED


def test_fidelity_failed_when_bytes_do_not_match():
    result = classify_fidelity(
        bytes_match=False, source_available=True, has_stored_hash=False,
        detail="regenerated bytes differ at offset 40",
    )
    assert result.outcome == FIDELITY_FAILED


def test_fidelity_unverifiable_when_nothing_to_compare_against():
    result = classify_fidelity(
        bytes_match=None, source_available=False, has_stored_hash=False,
        detail="source file deleted, no per-line hash on record",
    )
    assert result.outcome == FIDELITY_UNVERIFIABLE


def test_fidelity_verified_can_use_a_stored_hash_without_the_source_file():
    """A previously captured hash is a real verification even after the
    source file is gone - this is the whole point of capturing hashes
    before cleanup."""
    result = classify_fidelity(
        bytes_match=True, source_available=False, has_stored_hash=True,
        detail="matched stored sha256, source file no longer present",
    )
    assert result.outcome == FIDELITY_VERIFIED
    assert result.source_available is False


def test_fidelity_refuses_to_invent_a_verdict_when_a_comparison_was_skippable():
    """bytes_match=None with a hash or source actually available means
    the caller skipped a comparison it could have run - that is a caller
    bug, not a CANNOT-DETERMINE this function may paper over."""
    with pytest.raises(ValueError):
        classify_fidelity(
            bytes_match=None, source_available=True, has_stored_hash=False,
            detail="did not bother checking",
        )
    with pytest.raises(ValueError):
        classify_fidelity(
            bytes_match=None, source_available=False, has_stored_hash=True,
            detail="did not bother checking",
        )


def test_fidelity_check_rejects_blank_detail():
    with pytest.raises(ValueError):
        classify_fidelity(
            bytes_match=True, source_available=True, has_stored_hash=False,
            detail="",
        )


def test_all_fidelity_outcomes_are_distinct_and_three():
    assert len(ALL_FIDELITY_OUTCOMES) == 3
    assert len(set(ALL_FIDELITY_OUTCOMES)) == 3


# ---- GatedItem invariants -----------------------------------------------

def test_gated_item_requires_at_least_one_condition_while_gated():
    with pytest.raises(ValueError):
        GatedItem(item_ref="msg:1", conditions=(), status=STATUS_GATED)


def test_gated_item_rejects_unregistered_condition_code():
    with pytest.raises(ValueError):
        GatedItem(item_ref="msg:1", conditions=("not_a_real_code",))


def test_resolved_item_may_have_zero_conditions():
    item = GatedItem(
        item_ref="msg:1", conditions=(), status=STATUS_RESOLVED,
    )
    assert item.status == STATUS_RESOLVED


def test_candidate_confidence_must_be_in_unit_interval():
    Candidate(ref="session:1", reason="matches agent_id", confidence=0.0)
    Candidate(ref="session:1", reason="matches agent_id", confidence=1.0)
    with pytest.raises(ValueError):
        Candidate(ref="session:1", reason="bad", confidence=1.5)
    with pytest.raises(ValueError):
        Candidate(ref="session:1", reason="bad", confidence=-0.1)


def test_gate_decision_requires_a_reason_and_timestamp():
    with pytest.raises(ValueError):
        GateDecision("human", "resolve", "session:1", "", "2026-08-29T00:00:00Z")
    with pytest.raises(ValueError):
        GateDecision("human", "resolve", "session:1", "matched", "")


def test_gate_decision_rejects_unknown_action():
    with pytest.raises(ValueError):
        GateDecision("human", "delete", None, "no", "2026-08-29T00:00:00Z")


# ---- apply_decision: pure, appends to audit trail, clears conditions ---

def test_apply_decision_resolves_and_clears_all_active_conditions():
    item = GatedItem(
        item_ref="msg:1",
        conditions=(GATE_DANGLING_PARENT, GATE_TOOL_CALL_WITHOUT_RESULT),
        candidates=(Candidate("session:5", "same agent_id"),),
    )
    decision = GateDecision(
        actor="jsugamele", action="resolve", chosen_ref="session:5",
        reason="confirmed same agent_id and adjacent timestamp",
        timestamp="2026-08-29T10:00:00Z",
    )
    resolved = apply_decision(item, decision)
    assert resolved.status == STATUS_RESOLVED
    assert resolved.conditions == ()
    assert resolved.decisions == (decision,)
    # original untouched - pure function
    assert item.status == STATUS_GATED
    assert item.conditions == (GATE_DANGLING_PARENT, GATE_TOOL_CALL_WITHOUT_RESULT)


def test_apply_decision_dismiss_also_resolves_without_a_chosen_ref():
    item = GatedItem(item_ref="msg:1", conditions=(GATE_DANGLING_PARENT,))
    decision = GateDecision(
        actor="jsugamele", action="dismiss", chosen_ref=None,
        reason="genuinely orphaned, source file confirms no parent existed",
        timestamp="2026-08-29T10:00:00Z",
    )
    resolved = apply_decision(item, decision)
    assert resolved.status == STATUS_RESOLVED
    assert resolved.conditions == ()


def test_apply_decision_appends_rather_than_replaces_the_audit_trail():
    item = GatedItem(item_ref="msg:1", conditions=(GATE_DANGLING_PARENT,))
    d1 = GateDecision("human_a", "resolve", "session:1", "first guess", "t1")
    once = apply_decision(item, d1)
    d2 = GateDecision(
        "human_b", "supersede", "session:2",
        "human_a was wrong, real parent is session:2", "t2",
    )
    twice = apply_decision(once, d2)
    assert twice.decisions == (d1, d2)


# ---- auto_resolve: only clears codes that are BOTH active and auto ----

def test_auto_resolve_clears_an_auto_resolvable_active_condition():
    item = GatedItem(item_ref="msg:1", conditions=(GATE_DANGLING_PARENT,))
    resolved = auto_resolve(item, [GATE_DANGLING_PARENT], timestamp="2026-08-29T10:00:00Z")
    assert resolved.status == STATUS_AUTO_RESOLVED
    assert resolved.conditions == ()
    assert resolved.decisions[-1].actor == "auto"


def test_auto_resolve_leaves_non_auto_resolvable_conditions_in_place():
    from src.core.message_gate_contract import GATE_DUPLICATE_UUID_BODY_CONFLICT
    assert GATE_DUPLICATE_UUID_BODY_CONFLICT not in AUTO_RESOLVABLE_CODES
    item = GatedItem(
        item_ref="msg:1", conditions=(GATE_DUPLICATE_UUID_BODY_CONFLICT,),
    )
    unchanged = auto_resolve(item, [GATE_DUPLICATE_UUID_BODY_CONFLICT], timestamp="2026-08-29T10:00:00Z")
    assert unchanged.status == STATUS_GATED
    assert unchanged.conditions == (GATE_DUPLICATE_UUID_BODY_CONFLICT,)
    assert unchanged.decisions == ()


def test_auto_resolve_ignores_a_code_the_item_does_not_currently_have():
    """A caller bug (naming a code this item was never gated for) must
    not silently manufacture a resolution."""
    item = GatedItem(item_ref="msg:1", conditions=(GATE_DANGLING_PARENT,))
    unchanged = auto_resolve(item, ["unrootable_session"], timestamp="2026-08-29T10:00:00Z")
    assert unchanged is item or (
        unchanged.conditions == item.conditions
        and unchanged.status == item.status
        and unchanged.decisions == item.decisions
    )


def test_auto_resolve_partial_clear_stays_gated_with_remainder():
    item = GatedItem(
        item_ref="msg:1",
        conditions=(GATE_DANGLING_PARENT, GATE_TOOL_CALL_WITHOUT_RESULT),
    )
    result = auto_resolve(item, [GATE_DANGLING_PARENT], timestamp="2026-08-29T10:00:00Z")
    assert result.status == STATUS_GATED
    assert result.conditions == (GATE_TOOL_CALL_WITHOUT_RESULT,)


# ---- reaper interlock: totality over (status, signal) ------------------

def test_reap_blocked_while_gated_regardless_of_signal():
    item = GatedItem(item_ref="s:1", conditions=(GATE_DANGLING_PARENT,))
    signal = DisposabilitySignal(DISPOSABILITY_HUMAN_DECISION, "owner confirmed disposable")
    assert reap_eligibility(item, signal) == REAP_BLOCKED_GATED
    assert reap_eligibility(item, None) == REAP_BLOCKED_GATED


def test_reap_blocked_when_resolved_but_no_signal():
    item = GatedItem(item_ref="s:1", conditions=(), status=STATUS_RESOLVED)
    assert reap_eligibility(item, None) == REAP_BLOCKED_NO_SIGNAL


def test_reap_eligible_only_when_resolved_and_signal_present():
    item = GatedItem(item_ref="s:1", conditions=(), status=STATUS_RESOLVED)
    signal = DisposabilitySignal(DISPOSABILITY_HUMAN_DECISION, "owner confirmed disposable")
    assert reap_eligibility(item, signal) == REAP_ELIGIBLE


def test_reap_eligibility_covers_all_four_status_signal_combinations():
    """Totality: gated x {signal, no signal} and resolved x {signal, no
    signal} - all four must map somewhere in ALL_REAP_VERDICTS, and the
    absence-of-link case must never be mistaken for a positive signal."""
    gated = GatedItem(item_ref="s:1", conditions=(GATE_DANGLING_PARENT,))
    resolved = GatedItem(item_ref="s:2", conditions=(), status=STATUS_RESOLVED)
    signal = DisposabilitySignal(DISPOSABILITY_HUMAN_DECISION, "confirmed")
    results = {
        reap_eligibility(gated, None),
        reap_eligibility(gated, signal),
        reap_eligibility(resolved, None),
        reap_eligibility(resolved, signal),
    }
    assert results <= set(ALL_REAP_VERDICTS)
    assert REAP_ELIGIBLE in results
    assert REAP_BLOCKED_GATED in results
    assert REAP_BLOCKED_NO_SIGNAL in results


def test_disposability_signal_requires_nonblank_evidence():
    with pytest.raises(ValueError):
        DisposabilitySignal(DISPOSABILITY_HUMAN_DECISION, "")


def test_disposability_signal_rejects_unknown_kind():
    with pytest.raises(ValueError):
        DisposabilitySignal("vibes", "felt disposable")


def test_all_disposability_signal_kinds_are_positive_evidence_not_absence():
    """Documents the interlock's core rule as an executable assertion:
    none of the recognised kinds is phrased as an absence-of-link."""
    for kind in ALL_DISPOSABILITY_SIGNAL_KINDS:
        assert "no_link" not in kind
        assert "unlinked" not in kind
        assert "orphan" not in kind
