"""Build the one ``Settings`` instance, or fail loudly and legibly.

Carved out of the flat ``src/config.py`` by slice S5 of
``.claude/notes/backend-decomposition-plan.md``. The construction is
byte-equivalent to what sat at the bottom of that file.

**A CONFIGURATION FAILURE MUST NOT BE A TRACEBACK.** This runs at import,
under launchd, inside an Electron wrapper, so the only channels that
reach a human are stderr and a file. Both are used, and the process exits
non-zero rather than limping on with a half-built settings object that
would fail somewhere unrelated an hour later.
"""

from __future__ import annotations

import sys
from pathlib import Path

from src.config.settings import Settings

#: Where the failure detail is written when stderr is not being read,
#: which under launchd and Electron is the normal case.
ERROR_LOG_PATH = Path("/tmp/cloude-code-startup-error.log")


def _error_message(error: Exception) -> str:
    """The text a human sees when configuration will not load.

    Inputs: error (Exception) - whatever pydantic refused on.
    Output: str - the full banner, ready for stderr and the log file.
    """
    return f"""
========================================
CLOUDE CODE - CONFIGURATION ERROR
========================================

Failed to load configuration from .env file.

Error: {str(error)}

This usually means:
1. Required fields are missing from .env (DEFAULT_WORKING_DIR, LOG_DIRECTORY)
2. Required auth fields are empty (TOTP_SECRET, JWT_SECRET)
3. .env file is malformed or has invalid values

To fix:
1. Run setup_auth.py to regenerate .env with all required fields
2. Or manually edit .env and ensure all required fields are present

Required fields:
- DEFAULT_WORKING_DIR (path to projects directory)
- LOG_DIRECTORY (path to logs directory)
- TOTP_SECRET (generated by setup_auth.py)
- JWT_SECRET (generated by setup_auth.py)

========================================
"""


def build_settings() -> Settings:
    """Construct the process-wide settings object, or exit.

    Description: the catch is deliberately broad because it is the
      OUTERMOST frame of configuration loading - a missing env field, an
      unreadable ``.env``, a validator raising on a value - and every one
      of them has the same right answer, which is to tell the user what
      to run and stop. It does not swallow: the message names the error
      and the process exits 1.
    Inputs: none.
    Output: Settings.
    Raises:
        SystemExit: always, when configuration cannot be loaded.
    Example: settings = build_settings()
    """
    try:
        return Settings()
    except Exception as error:  # noqa: BLE001 - outermost frame, see above
        message = _error_message(error)
        # stderr is captured by the Electron app logs.
        print(message, file=sys.stderr)
        try:
            ERROR_LOG_PATH.write_text(message)
            print(f"\nError details written to: {ERROR_LOG_PATH}", file=sys.stderr)
        except OSError:
            # Nowhere to write the detail. stderr already carries it, and
            # failing to log the failure must not change the exit path.
            pass
        sys.exit(1)
