"""What one record in a Claude Code transcript says about a turn.

The reading half of the seed ladder. ``session_status_seed`` decides what
EVIDENCE is worth; this file decides what the evidence SAYS, and holds
every record shape so a claude version that changes one has exactly one
file to be corrected in.

THREE VALUES, NEVER TWO. :func:`classify_record` answers True (this
record ends a turn), False (this record opens or continues one) or None
(this record says nothing either way). The third is what most records
are - attachments, summaries, file-history snapshots, queue operations,
mode records - and collapsing it into either of the others is how a
ladder starts inventing boundaries. :func:`classify_tail_records` walks
BACKWARDS and stops at the first decidable record, so the NEWEST evidence
wins and an old end-of-turn can never outrank a newer prompt. That is the
same ordering ``session_startup_gate`` uses when it reads a hook before
it reads the scrollback: old evidence is stale evidence.

Shapes verified against the live corpus 2026-09-08, claude 2.1.259 /
2.1.261 / 2.1.263, over a 400-transcript sample. That sample is also the
standing negative control for this file: it splits 172 at_rest / 70
in_flight / 158 no_marker, so the ladder demonstrably REFUSES rather than
always finding something. A matcher that always finds something is worse
than useless, and this one has a number attached.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Optional, Sequence


# ---------------------------------------------------------------------
# What the tail of a transcript said. FIVE outcomes, and the last two are
# separate on purpose: "there is no transcript" and "there is one and it
# could not be read" are different facts about the world, and only the
# first is a measurement.
# ---------------------------------------------------------------------

#: The newest decidable record ends a turn, and nothing follows it.
TAIL_AT_REST: str = "at_rest"

#: The newest decidable record is a user prompt, a tool result, or an
#: assistant turn that stopped to call a tool. A turn is in flight, or
#: was when the file was last appended to. SEEDS NOTHING - see the module
#: docstring on why work may not be claimed from a file.
TAIL_IN_FLIGHT: str = "in_flight"

#: The window was read and holds no decidable record. A DEFINITE negative
#: about the window, and NOT a claim about the conversation: the marker
#: may sit further back than the bound.
TAIL_NO_MARKER: str = "no_marker"

#: A MEASURED absence: no transcript for this conversation is on this
#: machine. Distinct from the next one, and neither is evidence of rest.
TAIL_ABSENT: str = "absent"

#: The transcript exists (or its presence could not be established) and
#: could not be read. NOT AN ABSENCE, and never an answer.
TAIL_UNREADABLE: str = "unreadable"

# ---------------------------------------------------------------------
# Transcript record shapes. Verified against the live corpus 2026-09-08
# on claude 2.1.259 / 2.1.261 / 2.1.263.
# ---------------------------------------------------------------------

#: ``system`` records whose presence means the turn ENDED. ``turn_duration``
#: is written when a turn completes; ``stop_hook_summary`` is written when
#: the Stop hook chain has run. Either one is the end of a turn stated by
#: claude itself, which is why this rung does not have to infer it.
REST_SYSTEM_SUBTYPES: frozenset[str] = frozenset(
    {"turn_duration", "stop_hook_summary"}
)

#: ``message.stop_reason`` values that end a turn. ``end_turn`` is the
#: ordinary one; ``stop_sequence`` ends it too.
REST_STOP_REASONS: frozenset[str] = frozenset({"end_turn", "stop_sequence"})

#: ``message.stop_reason`` values that mean the turn is NOT over: the
#: assistant stopped only to call a tool, or ran out of room mid-answer.
IN_FLIGHT_STOP_REASONS: frozenset[str] = frozenset({"tool_use", "max_tokens"})

#: The ``system`` subtype claude writes when it has HANDLED A SLASH
#: COMMAND ITSELF. Undecidable, deliberately, and it is the one record
#: type this ladder had to be corrected about. A local command never
#: reaches the model - CLAUDE.md already records that "claude intercepts
#: slash commands before they become prompts", which is why no hook event
#: carries a ``/rename`` - so this record is neither the start of a turn
#: nor the end of one, and reading it either way would be inventing a
#: boundary claude did not write.
LOCAL_COMMAND_SUBTYPE: str = "local_command"

#: Envelopes claude wraps around its OWN bookkeeping for an intercepted
#: slash command. A ``user`` record carrying one was not typed at the
#: model, and the caveat envelope says so in words: "The messages below
#: were generated by the user while running a local command. DO NOT
#: respond to these messages."
#:
#: MEASURED, AND IT CHANGED THE ANSWER. On live 2026-09-08 the only two
#: sessions this ladder refused were both parked at an empty ``>``
#: prompt, and both were refused because their newest ``user`` record was
#: a ``/rename`` envelope - read as a prompt, so read as a turn in
#: flight, forever, on two sessions that had been resting for days.
#: Treating these as UNDECIDABLE rather than as rest is the conservative
#: half of the fix: the walk continues back to a boundary claude really
#: wrote, and nothing here ever asserts rest on its own.
LOCAL_COMMAND_MARKERS: tuple[str, ...] = (
    "<command-name>",
    "<command-message>",
    "<command-args>",
    "<local-command-caveat>",
    "<local-command-stdout>",
    "<local-command-stderr>",
)


@dataclass(frozen=True)
class TranscriptRest:
    """What the tail of one transcript says about rest.

    Description: the return of :func:`classify_tail_records`. Frozen
      because it reports a measurement of a file, not a plan.

      - ``verdict``: one of the five ``TAIL_*`` constants.
      - ``at``: the timestamp of the record that decided it, on
        :data:`TAIL_AT_REST` only. Timezone-aware, or None when the
        record carried no readable timestamp.
      - ``detail``: a plain sentence naming why.
    Inputs: n/a.
    Output: n/a (data holder).
    """

    verdict: str
    at: Optional[datetime] = None
    detail: Optional[str] = None

    @property
    def at_rest(self) -> bool:
        """True only on a measured end-of-turn.

        Description: the one-line test a seed may be built on.
          Deliberately False for every other verdict, so an unreadable
          file can never be spelled the same way as a resting one.
        Inputs: n/a.
        Output: bool.
        Example: classify_tail_records(recs).at_rest
        """
        return self.verdict == TAIL_AT_REST


def parse_timestamp(raw: Any) -> Optional[datetime]:
    """Read an ISO timestamp off a record or a row, timezone-aware.

    Description: tolerates the trailing ``Z`` transcript records use and
      the offset-bearing form ``activity_persist`` writes. A naive value
      is read as UTC, matching ``activity_persist._parse``. NEVER RAISES:
      an unparseable value is None, which every caller treats as "not
      dated" rather than as a time.
    Inputs: raw (Any) - the candidate value, usually str or None.
    Output: datetime | None - timezone-aware, or None.
    Example: parse_timestamp('2026-09-04T19:39:04.864Z').tzinfo is not None
    """
    if not isinstance(raw, str) or not raw.strip():
        return None
    text = raw.strip()
    if text.endswith(("Z", "z")):
        text = text[:-1] + "+00:00"
    try:
        parsed = datetime.fromisoformat(text)
    except ValueError:
        return None
    if parsed.tzinfo is None:
        parsed = parsed.replace(tzinfo=timezone.utc)
    return parsed


def is_local_command_envelope(record: Any) -> bool:
    """Is this ``user`` record claude's bookkeeping for a slash command.

    Description: PURE. Reads the record's message text - a plain string
      or the concatenation of its ``text`` blocks - and looks for any of
      :data:`LOCAL_COMMAND_MARKERS` at its head. Only the HEAD, so a
      genuine prompt that quotes one of these tags further down (asking
      about this very code, say) is still read as a prompt.
    Inputs: record (Any) - one parsed jsonl object.
    Output: bool - True only for an envelope claude wrote about itself.
    Example:
      is_local_command_envelope({'message': {'content': '<command-name>/rename</command-name>'}})
    """
    message = record.get("message") if isinstance(record, dict) else None
    content = message.get("content") if isinstance(message, dict) else None
    if isinstance(content, str):
        text = content
    elif isinstance(content, list):
        text = "".join(
            block.get("text", "")
            for block in content
            if isinstance(block, dict) and isinstance(block.get("text"), str)
        )
    else:
        return False
    head = text.lstrip()[:200]
    return any(head.startswith(marker) for marker in LOCAL_COMMAND_MARKERS)


def classify_record(record: Any) -> Optional[bool]:
    """Does one transcript record end a turn, continue one, or say nothing.

    Description: PURE, and deliberately three-valued. ``None`` means the
      record is UNDECIDABLE - an attachment, a summary, a custom-title, a
      system record of some other subtype - and the caller keeps walking
      backwards rather than treating silence as an answer.

      SIDECHAIN RECORDS ARE UNDECIDABLE, and that is the subtle one. A
      record with ``isSidechain`` true belongs to a SUBAGENT running
      inside the parent's turn, so its ``end_turn`` says the subagent
      finished and says nothing about the conversation the user is
      watching. Reading one as rest would paint a session idle in the
      middle of the exact kind of work that takes longest.
    Inputs: record (Any) - one parsed jsonl object.
    Output: bool | None - True at rest, False in flight, None undecidable.
    Example: classify_record({'type': 'user'}) -> False
    """
    if not isinstance(record, dict):
        return None
    if record.get("isSidechain") is True:
        return None

    kind = record.get("type")

    if kind == "system":
        subtype = record.get("subtype")
        if isinstance(subtype, str) and subtype in REST_SYSTEM_SUBTYPES:
            return True
        # ``local_command`` falls through to undecidable along with every
        # other subtype. Named in LOCAL_COMMAND_SUBTYPE so a reader can
        # see it was considered rather than overlooked.
        return None

    if kind == "assistant":
        message = record.get("message")
        reason = message.get("stop_reason") if isinstance(message, dict) else None
        if isinstance(reason, str):
            if reason in REST_STOP_REASONS:
                return True
            if reason in IN_FLIGHT_STOP_REASONS:
                return False
        return None

    if kind == "user":
        if is_local_command_envelope(record):
            # NOT A PROMPT. claude wrote this about a slash command it
            # handled itself; the model never saw it. See
            # LOCAL_COMMAND_MARKERS for the two live sessions this got
            # wrong before it was measured.
            return None
        # Otherwise a user record is either the prompt that OPENS a turn
        # or the tool_result that continues one. Both mean a turn was
        # live when the file was last written, and neither may seed
        # anything.
        return False

    return None


def classify_tail_records(records: Sequence[Any]) -> TranscriptRest:
    """What the newest decidable record in a tail window says about rest.

    Description: PURE. Walks the window BACKWARDS and stops at the first
      record :func:`classify_record` can decide, so the NEWEST evidence
      wins and an older end-of-turn can never outrank a newer prompt.
      That ordering is the same reason ``session_startup_gate`` reads a
      hook before it reads the scrollback: old evidence is stale evidence,
      and a ladder that met it first would pin a session forever.

      A window with nothing decidable in it answers
      :data:`TAIL_NO_MARKER`, never ``at_rest``. The 64 KB bound means a
      single large tool result can fill the whole window, and "the marker
      is further back than I looked" is not "there is no marker".
    Inputs: records (Sequence[Any]) - parsed jsonl objects, oldest first.
    Output: TranscriptRest.
    Example: classify_tail_records([{'type': 'user'}]).verdict -> 'in_flight'
    """
    for record in reversed(list(records or ())):
        verdict = classify_record(record)
        if verdict is None:
            continue
        if verdict:
            return TranscriptRest(
                TAIL_AT_REST,
                at=parse_timestamp(record.get("timestamp")),
                detail=(
                    "the newest decidable record in the transcript tail "
                    "ends a turn and nothing follows it, so this "
                    "conversation is at rest"
                ),
            )
        return TranscriptRest(
            TAIL_IN_FLIGHT,
            detail=(
                "the newest decidable record in the transcript tail "
                "opens or continues a turn, so nothing is seeded - a "
                "file cannot carry the heartbeat a working claim needs"
            ),
        )
    return TranscriptRest(
        TAIL_NO_MARKER,
        detail=(
            "the transcript tail that was read holds no record this "
            "ladder can decide, which is not evidence that none exists "
            "further back than the bound"
        ),
    )
