"""Read one Claude Code transcript far enough to rebuild a session row.

WHAT A TRANSCRIPT IS, FOR THIS PURPOSE. A ``.jsonl`` under
``~/.claude/projects/<slug>/<uuid>.jsonl``, one JSON object per line,
append-only, whose records carry a ``cwd``, a ``sessionId`` and a
``timestamp``. The largest on the owner's box is 73 MB, so NOTHING here
reads a whole file: the head is scanned for the first records that carry
the identifying fields, and the tail is read for the last timestamp and
the newest ``custom-title``.

THREE KINDS OF FILE LIVE IN THAT DIRECTORY, not two, and the third is
the surprise. Measured 2026-09-08 over 1,486 top-level files: 1,167
carry a conversation and 319 carry NO ``cwd`` ANYWHERE IN THE FILE.
Every one of those 319 is made only of ``file-history-snapshot``,
``summary``, ``bridge-session`` records or nothing at all - Claude Code
bookkeeping that happens to be stored as a transcript. They have no
working directory, no conversation and no timestamps of one.

So :data:`TRANSCRIPT_NO_CONVERSATION` is a NAMED OUTCOME rather than a
silent skip. It is not the scratch-path exclusion (a real conversation in
a directory we do not want a row for) and it is not a read failure. A
matcher that always finds something is worse than useless, and a file
with nothing in it is the case that would make one.

NEVER RAISES. Every filesystem and decode failure becomes
:data:`TRANSCRIPT_UNREADABLE` with a sentence, because a corpus scan over
19,000 files must not die on the one that was being written when it was
opened.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass
from typing import Optional

from src.core.claude_title_sync import read_newest_custom_title

#: The file carries a conversation: a ``cwd`` was found.
TRANSCRIPT_READ = "read"

#: THE FILE HOLDS NO CONVERSATION. No record anywhere in it carries a
#: ``cwd``, so there is no working directory, no project and nothing to
#: import. See the module docstring for what these files actually are.
TRANSCRIPT_NO_CONVERSATION = "no_conversation"

#: COULD NOT LOOK. A filesystem error. Distinct from
#: :data:`TRANSCRIPT_NO_CONVERSATION`, which is a completed measurement.
TRANSCRIPT_UNREADABLE = "unreadable"

#: How many lines of a transcript are scanned looking for its ``cwd``,
#: ``sessionId`` and first user text. Bounded so one pathological file
#: cannot stall a pass over the whole corpus. Measured over the live
#: corpus: every file that has a ``cwd`` at all has one in its first
#: record, and no file was found whose cwd appeared later - the 319 with
#: none in the first 60 lines had none in the whole file either.
MAX_LINES_SCANNED = 200

#: Bytes read from the END of a transcript for the last timestamp. The
#: largest file in the owner's corpus is 73 MB, so reading whole files is
#: not an option and the tail is where the answer is.
TAIL_BYTES = 65536

#: Record types that are Claude Code bookkeeping rather than turns. A
#: file made only of these carries no conversation.
BOOKKEEPING_TYPES = frozenset(
    {"file-history-snapshot", "summary", "bridge-session"}
)

#: A ``<scheduled-task name="X" file="...">`` envelope. Claude Code opens
#: a scheduled run with one, and the NAME is the best possible title for
#: that conversation - it is literally what the session is for. Measured
#: on the live corpus 2026-09-08: 251 of 943 conversations open with one.
SCHEDULED_TASK = re.compile(r'\A<scheduled-task\s+name="([^"]+)"')

#: Wrappers Claude Code injects into the user turn that the user did not
#: type. A record made only of one of these is not the owner's first
#: message and titling a conversation with it would name 46 of his
#: sessions "Caveat: The messages below were generated by the user while
#: running local commands" - a title that identifies nothing.
#:
#: The test is on the WHOLE record, not on a prefix: a real prompt that
#: happens to follow a system-reminder in the same record still carries
#: prose, and that prose is the title.
SYNTHETIC_ENVELOPE = re.compile(r"<([a-zA-Z][\w-]*)\b[^>]*>.*?</\1>", re.DOTALL)

#: A self-closing or unterminated envelope - the shape ``<ide_opened_file
#: ...>`` takes when it carries no body.
SYNTHETIC_BARE_TAG = re.compile(r"\A<[a-zA-Z][\w-]*\b[^>]*>\Z", re.DOTALL)


@dataclass(frozen=True)
class TranscriptFacts:
    """Everything one transcript can say about the session it recorded.

    Description: frozen because it reports a measurement of a file, not
      a plan. Every field except ``status`` and ``path`` may be None,
      and None always means "the file did not say", never a default.
    Attributes:
        path: the transcript's absolute path.
        uuid: the file's stem, which is Claude Code's session id for it.
        status: one of the three ``TRANSCRIPT_*`` constants.
        session_id: the ``sessionId`` the records self-report. Usually
            equal to ``uuid``; kept separate because a disagreement is a
            fact worth being able to see rather than one to assume away.
        cwd: the working directory the records recorded, VERBATIM - the
            literal string Claude Code was started in, not a resolved
            one. Canonicalising is the caller's job and the caller needs
            the original to do it.
        first_ts: ISO-8601 timestamp of the earliest record carrying one.
        last_ts: ISO-8601 timestamp of the latest record in the tail.
        custom_title: the newest ``custom-title`` record's name, which is
            what ``/rename`` writes. Outranks everything else as a title
            because the owner typed it.
        first_user_text: the text of the first top-level user message,
            untruncated. The fallback title.
        detail: a plain sentence, on the two non-READ statuses.
    """

    path: str
    uuid: str
    status: str
    session_id: Optional[str] = None
    cwd: Optional[str] = None
    first_ts: Optional[str] = None
    last_ts: Optional[str] = None
    custom_title: Optional[str] = None
    first_user_text: Optional[str] = None
    detail: Optional[str] = None

    @property
    def is_conversation(self) -> bool:
        """True only when a working directory was actually read.

        Description: the one test an import decision may be built on.
          Deliberately False for BOTH non-READ statuses, so "no
          conversation in it" and "could not look" cannot be confused at
          a call site - they are told apart by ``status``, never by this.
        Inputs: n/a.
        Output: bool.
        Example: read_transcript_facts(p).is_conversation
        """
        return self.status == TRANSCRIPT_READ


def _user_text(record: dict) -> Optional[str]:
    """The plain text of one top-level user record, or None.

    Description: Claude Code writes a user message's ``content`` either
      as a string or as a list of typed blocks; only ``text`` blocks are
      prose. A sidechain record is a SUBAGENT's turn, not the owner's,
      so it is skipped - titling a conversation with a subagent's
      internal prompt would name it after something the user never
      typed.
    Inputs: record (dict) - one parsed transcript line.
    Output: str | None - the text, stripped, or None.
    Example: _user_text({'type': 'user', 'message': {'content': 'hi'}})
    """
    if record.get("type") != "user" or record.get("isSidechain"):
        return None
    message = record.get("message")
    if not isinstance(message, dict):
        return None
    content = message.get("content")
    if isinstance(content, str):
        text = content.strip()
    elif isinstance(content, list):
        parts = [
            block.get("text", "")
            for block in content
            if isinstance(block, dict) and block.get("type") == "text"
        ]
        text = "\n".join(part for part in parts if part).strip()
    else:
        return None
    if not text:
        return None

    scheduled = SCHEDULED_TASK.match(text)
    if scheduled:
        return f"scheduled task: {scheduled.group(1)}"

    # A record that is NOTHING BUT injected envelopes is not a message the
    # owner typed, so the scan keeps going to the next user record - the
    # same rule that skips a sidechain, for the same reason.
    stripped = SYNTHETIC_ENVELOPE.sub("", text).strip()
    if not stripped or SYNTHETIC_BARE_TAG.match(stripped):
        return None
    return stripped


def _read_head(path: str) -> tuple:
    """Scan the head of a transcript for the identifying fields.

    Description: stops as soon as it has a cwd, a sessionId, a first
      timestamp AND a first user text, so a long conversation costs a
      handful of lines rather than a full read. A line that does not
      parse is skipped in silence - a transcript is append-only and its
      last line is routinely a partial write.
    Inputs: path (str).
    Output: tuple - (cwd, session_id, first_ts, first_user_text, saw_any)
      where ``saw_any`` reports whether any line parsed at all.
    """
    cwd = session_id = first_ts = first_user = None
    saw_any = False
    with open(path, "rb") as handle:
        for index, raw in enumerate(handle):
            if index >= MAX_LINES_SCANNED:
                break
            raw = raw.strip()
            if not raw:
                continue
            try:
                record = json.loads(raw)
            except (ValueError, UnicodeDecodeError):
                continue
            if not isinstance(record, dict):
                continue
            saw_any = True
            if cwd is None and isinstance(record.get("cwd"), str) and record["cwd"]:
                cwd = record["cwd"]
            if session_id is None and isinstance(record.get("sessionId"), str):
                session_id = record["sessionId"] or None
            if first_ts is None and isinstance(record.get("timestamp"), str):
                first_ts = record["timestamp"] or None
            if first_user is None:
                first_user = _user_text(record)
            if cwd and session_id and first_ts and first_user:
                break
    return cwd, session_id, first_ts, first_user, saw_any


def _read_last_timestamp(path: str, size: int) -> Optional[str]:
    """The newest ``timestamp`` in the tail of a transcript.

    Description: reads at most :data:`TAIL_BYTES` from the end. The
      window's first line is dropped when the read did not start at byte
      0, because a mid-file start lands inside a line and half a record
      is not a record.
    Inputs: path (str), size (int) - the file's size in bytes.
    Output: str | None - ISO-8601, or None when the tail carries none.
    """
    start = max(0, size - TAIL_BYTES)
    with open(path, "rb") as handle:
        if start:
            handle.seek(start)
        window = handle.read()
    lines = window.split(b"\n")
    if start > 0 and lines:
        lines = lines[1:]
    newest = None
    for raw in lines:
        raw = raw.strip()
        if not raw:
            continue
        try:
            record = json.loads(raw)
        except (ValueError, UnicodeDecodeError):
            continue
        if isinstance(record, dict) and isinstance(record.get("timestamp"), str):
            if record["timestamp"]:
                newest = record["timestamp"]
    return newest


def read_transcript_facts(path: str) -> TranscriptFacts:
    """Everything one transcript file can say about its session.

    Description: three reads over one file - a bounded head scan, a
      bounded tail read for the last timestamp, and
      ``claude_title_sync.read_newest_custom_title`` for the name the
      owner may have typed. That last one is IMPORTED rather than
      re-implemented: it is already the single spelling of "what does a
      custom-title record look like", and a second copy here would
      eventually disagree with the hook path about what a rename is.

      A file with no ``cwd`` anywhere answers
      :data:`TRANSCRIPT_NO_CONVERSATION`. See the module docstring.
    Inputs: path (str) - the transcript ``.jsonl``.
    Output: TranscriptFacts - never raises.
    Example:
      read_transcript_facts('/x/-Users-x-p/abc.jsonl').cwd  # '/Users/x/p'
    """
    uuid = os.path.splitext(os.path.basename(path))[0]
    try:
        size = os.path.getsize(path)
        cwd, session_id, first_ts, first_user, saw_any = _read_head(path)
        last_ts = _read_last_timestamp(path, size)
    except OSError as exc:
        return TranscriptFacts(
            path=path,
            uuid=uuid,
            status=TRANSCRIPT_UNREADABLE,
            detail=f"the transcript could not be read: {exc.strerror or exc}",
        )

    if not cwd:
        return TranscriptFacts(
            path=path,
            uuid=uuid,
            status=TRANSCRIPT_NO_CONVERSATION,
            session_id=session_id,
            first_ts=first_ts,
            last_ts=last_ts,
            detail=(
                "no record in this file carries a cwd, so it holds no "
                "conversation - it is claude code bookkeeping "
                "(file-history-snapshot, summary or bridge-session "
                "records) stored as a transcript"
                if saw_any
                else "the file holds no parseable json records at all"
            ),
        )

    title_read = read_newest_custom_title(path)
    return TranscriptFacts(
        path=path,
        uuid=uuid,
        status=TRANSCRIPT_READ,
        session_id=session_id,
        cwd=cwd,
        first_ts=first_ts,
        last_ts=last_ts,
        custom_title=title_read.title if title_read.found else None,
        first_user_text=first_user,
    )
