#!/usr/bin/env python3
"""The roster of every subagent run ever observed, and why it is a text file.

THE OWNER OVERRULED THE OLD LIMIT, SO THIS IS THE ANSWER TO IT. The census used
to record subagent runs as a COUNT per source plus the stems of the few known to
be missing, on the reasoning that enumerating about 19,000 of them against about
1,300 conversations would produce a 450 KB JSON rewritten on every ingest. The
owner's rule, verbatim: "i also want to confirm all conversations are in the
database. even subagent because the archive viewer is an in depth detailed
viewer." So the coverage is not negotiable and the churn has to be solved
instead.

WHERE THE CHURN ACTUALLY WAS, MEASURED RATHER THAN ASSUMED. It was never the
count. It was per-entry MUTABLE METADATA multiplied by the count: every census
conversation entry carries ``sources``, ``first_observed`` and ``last_observed``,
and ``last_observed`` is restamped on every refresh. Nineteen thousand of those
is a nineteen-thousand-line diff every single run, forever.

THE FIX IS TO SPLIT IDENTITY FROM PROVENANCE.

  identity     this file. One stem per line, sorted, ASCII, LF. Nothing else -
               no timestamps, no source list, no sizes. A stem observed once is
               observed forever, so this set only ever GROWS and a refresh can
               only ever ADD lines. A refresh that observed twelve new subagent
               runs is a twelve line git diff. That is the whole trick.
  provenance   ``conversation_census.json["subagents"]``, unchanged: where to
               find it, how big it is and its sha256, kept ONLY for runs that
               are missing from the live archive. A run the archive already
               holds needs no recovery pointer, because it is in the archive.

WHY TEXT AND NOT GZIP. A gzip sidecar is a third the size and a binary blob in
git: every refresh is a whole-file binary diff and no reviewer can read it. The
point of committing this is that a human can grep it and a diff can be reviewed.

THE SET DIGEST IS A DRIFT ALARM, NOT A GAP FINDER, AND SAYING SO MATTERS.
:func:`set_digest` is recorded per source in the census. A static source - a
tarball manifest cut on 2026-08-30 - must produce the same digest every time it
is read. A changed digest means the artifact changed or the reader broke, and it
costs 64 bytes per source instead of 19,000 stems per source. It cannot tell you
WHICH stem moved. The roster is what does that.

A MISSING ROSTER IS NEVER A READING OF ZERO. :func:`read_roster` raises rather
than returning an empty set, because a checker that treated an absent roster as
"no subagent runs have ever existed" would answer ALL ACCOUNTED FOR on a machine
where the file had simply been deleted. An EMPTY roster is different and is
allowed: a real file holding no stems is a real reading of zero, and the return
carries ``complete`` so a caller can tell the two apart the way
``StatusMap.complete`` already does elsewhere in this project.
"""
from __future__ import annotations

import hashlib
import os
from typing import Iterable, List, Sequence, Set, Tuple

from conversation_sources import CannotEvaluate, is_subagent, stem_of

#: Committed beside the census. Named in exactly one place.
ROSTER_FILENAME = "subagent_roster.txt"

#: Lines beginning with this are commentary, not stems. A stem can never start
#: with it, so the two can never be confused.
COMMENT_PREFIX = "#"

#: Header written above the stems so the file explains itself to whoever opens
#: it without the module beside them.
ROSTER_HEADER: Tuple[str, ...] = (
    "# every subagent run (agent-*.jsonl) ever observed in any source.",
    "# one stem per line, sorted, append only. identity only: provenance for a",
    "# run MISSING from the live archive lives in conversation_census.json.",
    "# generated by build_conversation_census.py; read by",
    "# verify_all_conversations.py. do not hand edit.",
)


def set_digest(stems: Iterable[str]) -> str:
    """Hash a set of stems so two readings of one source can be compared.

    Description: order independent by construction - the input is sorted and
      deduplicated before hashing - so it is a digest of the SET, not of
      whatever order a reader happened to produce.
    Inputs:
      stems: any iterable of stems.
    Outputs:
      str: hex sha256 of the sorted unique stems, one per line, LF terminated.
    Example:
      >>> set_digest(["b", "a"]) == set_digest(["a", "b", "a"])
      True
    """
    digest = hashlib.sha256()
    for stem in sorted(set(s for s in stems if s)):
        digest.update(stem.encode("utf-8"))
        digest.update(b"\n")
    return digest.hexdigest()


def subagent_stems_from_paths(paths: Iterable[str]) -> Set[str]:
    """Reduce arbitrary transcript paths to the subagent stems among them.

    Inputs:
      paths: any iterable of paths or bare stems.
    Outputs:
      set: the stems that name subagent runs.
    Example:
      >>> sorted(subagent_stems_from_paths(["a/agent-1.jsonl", "a/b.jsonl"]))
      ['agent-1']
    """
    out: Set[str] = set()
    for path in paths:
        stem = stem_of(path.strip()) if path else ""
        if stem and is_subagent(stem):
            out.add(stem)
    return out


def read_roster(roster_path: str) -> Tuple[Set[str], bool]:
    """Read the roster, or refuse.

    Inputs:
      roster_path: path to the roster text file.
    Outputs:
      (stems, complete): the stems, and True because a successful read is a
        complete reading. The flag exists so a caller never has to infer
        completeness from emptiness.
    Raises:
      CannotEvaluate: the file is missing or unreadable. Not having looked is
        not a reading of zero.
    """
    if not os.path.exists(roster_path):
        raise CannotEvaluate(f"subagent roster not found: {roster_path}")
    try:
        with open(roster_path, "r", encoding="utf-8") as handle:
            lines = handle.read().splitlines()
    except OSError as exc:
        raise CannotEvaluate(f"subagent roster would not read: {exc}") from exc
    stems = {line.strip() for line in lines
             if line.strip() and not line.startswith(COMMENT_PREFIX)}
    return stems, True


def roster_lines(stems: Iterable[str]) -> List[str]:
    """Render the roster's exact file content as a list of lines.

    Inputs:
      stems: the stems to write.
    Outputs:
      list of str: the header lines followed by the sorted unique stems.
    """
    return list(ROSTER_HEADER) + sorted(set(s for s in stems if s))


def write_roster(roster_path: str, stems: Iterable[str]) -> dict:
    """Merge stems into the roster on disk, refusing to shrink it.

    Description: the roster is APPEND ONLY. A refresh that observed fewer
      subagent runs than the file already holds has not discovered that some
      stopped existing, it has failed to read something - a NAS that was down,
      a tarball manifest that did not open - and writing the smaller set would
      silently shrink the "ever observed" universe and hide a gap. So the union
      is written and a would-be shrink is reported rather than applied.
    Inputs:
      roster_path: file to write.
      stems: newly observed stems to merge in.
    Outputs:
      dict: {"before", "observed", "after", "added", "would_have_dropped",
             "sha256"}.
    Raises:
      OSError: the file could not be written.
    """
    try:
        previous, _complete = read_roster(roster_path)
    except CannotEvaluate:
        previous = set()
    observed = {s for s in stems if s}
    merged = previous | observed
    lines = roster_lines(merged)
    body = "\n".join(lines) + "\n"
    tmp = roster_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as handle:
        handle.write(body)
        handle.flush()
        os.fsync(handle.fileno())
    os.replace(tmp, roster_path)
    return {
        "before": len(previous),
        "observed": len(observed),
        "after": len(merged),
        "added": len(merged - previous),
        "would_have_dropped": len(previous - observed),
        "sha256": hashlib.sha256(body.encode("utf-8")).hexdigest(),
    }


def read_stem_file(path: str) -> Set[str]:
    """Read a one-per-line list of transcript paths or stems from disk.

    Description: the input for a source that cannot be re-read on a routine
      refresh, such as the 22 GB claude-history database or the 4.5 GB git
      history. The operator produces the list once and merges it in.
    Inputs:
      path: a newline delimited file of paths or stems.
    Outputs:
      set: every non-empty line, stripped.
    Raises:
      CannotEvaluate: the file is missing or unreadable.
    """
    if not os.path.exists(path):
        raise CannotEvaluate(f"stem file not found: {path}")
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as handle:
            return {line.strip() for line in handle if line.strip()}
    except OSError as exc:
        raise CannotEvaluate(f"stem file would not read: {exc}") from exc


def default_roster_path(census_path: str) -> str:
    """Locate the roster that belongs beside a given census file.

    Inputs:
      census_path: path to conversation_census.json.
    Outputs:
      str: the roster path in the same directory.
    Example:
      >>> default_roster_path("/a/conversation_census.json")
      '/a/subagent_roster.txt'
    """
    return os.path.join(os.path.dirname(os.path.abspath(census_path)),
                        ROSTER_FILENAME)
